import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Header,Footer,About,Testimonial,Work,Skills, } from '@/Container'
import { Navbar } from '@/components'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fitiavana`s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/profile.png" />
      </Head>
      <div className='app'>
            {/* Navbar */}
            <Navbar />
            {/* Header */}
            <Header />
            {/* About */}
            <About /> 
            {/* Work */}
            <Work />
            {/* Skills */}
            <Skills />
            {/* Testimonial */}
            <Testimonial />
            {/* Footer */}
            <Footer />
      </div>
    </>
  )
}
