name: Run linter and build

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4 # Updated to v4 for better performance

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Or specify your preferred version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Use an LTS version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run linters
        run: pnpm run lint
  
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: run-linters

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run build
        run: pnpm run build